CREATE DATABASE IF NOT EXISTS hua_shi_jie CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE hua_shi_jie;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE,
  email VARCHAR(128),
  registration_date DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS flowers (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) NOT NULL UNIQUE,
  family VARCHAR(128) NOT NULL,
  color VARCHAR(256) NOT NULL,
  blooming_period VARCHAR(128) NOT NULL,
  description TEXT NOT NULL,
  care_guide TEXT NOT NULL,
  flower_language TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS recognition_records (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  image_url VARCHAR(512),
  plant_id BIGINT,
  user_id BIGINT,
  confidence DECIMAL(5,2),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (plant_id) REFERENCES flowers(id) ON DELETE SET NULL ON UPDATE CASCADE,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL ON UPDATE CASCADE
);
